#+OPTIONS: toc:nil
#+TITLE: Assignment 3 Solutions
These solutions are incomplete
* Exercise 1.14
  Draw the tree illustrating the process generated by the =count-change=
  procedure of Section 1.2.2 in making change for 11 cents. What are the orders
  of the space and number of steps used by this process as the amount to be
  changed increases?
** Solution
   This is the tree illustrating the process generated by =count-change=:
   #+BEGIN_EXAMPLE
   (count-change 11)
   |
   (cc 11 5)__
   |          \
   (cc 11 4)   (cc -39 5)
   |       \___
   |           \
   (cc 11 3)   (cc -14 4)
   |       \_______________________________________________________
   |                                                               \
   (cc 11 2)                                                      (cc 1 3)
   |       \_________________________                              |     \__
   |                                 \                             |        \
   (cc 11 1)                        (cc 6 2)                      (cc 1 2) (cc -9 2)
   |       \___                      |     \__                     |     \__
   |           \                     |        \                    |        \
   (cc 11 0)   (cc 10 1)            (cc 6 1) (cc 1 2)             (cc 1 1) (cc -4 2)
            __/ |                 __/ |       |     \__            |     \__
           /    |                /    |       |        \           |        \
   (cc 10 0)   (cc 9 1)  (cc 6 0)   (cc 5 1) (cc 1 1) (cc -4 2)   (cc 1 0) (cc 0 1)
            __/ |                 __/ |       |     \__
           /    |                /    |       |        \
   (cc 9 0)    (cc 8 1)  (cc 5 0)   (cc 4 1) (cc 1 0) (cc 0 1)
            __/ |                 __/ |
           /    |                /    |
   (cc 8 0)    (cc 7 1)  (cc 4 0)   (cc 3 1)
            __/ |                 __/ |
           /    |                /    |
   (cc 7 0)    (cc 6 1)  (cc 3 0)   (cc 2 1)
            __/ |                 __/ |
           /    |                /    |
   (cc 6 0)    (cc 5 1)  (cc 2 0)   (cc 1 1)
            __/ |                 __/ |
           /    |                /    |
   (cc 5 0)    (cc 4 1)  (cc 1 0)   (cc 0 1)
            __/ |
           /    |
   (cc 4 0)    (cc 3 1)
            __/ |
           /    |
   (cc 3 0)    (cc 2 1)
            __/ |
           /    |
   (cc 2 0)    (cc 1 1)
            __/ |
           /    |
   (cc 1 0)    (cc 0 1)
   #+END_EXAMPLE
   Let /a/ be the amount to be changed, then the space complexity is \(
   \Theta(a) \) while the time complexity is \( \Theta(a^5) \).
* Exercise 1.15
  The sine of an angle (specified in radians) can be computed by making use of
  the approximation \( \sin x \approx x \) if /x/ is sufficiently small, and the
  trigonometric identity
  \begin{equation}
  \sin x = 3 \sin (x/3) - 4 \sin^3 (x/3)
  \end{equation}
  to reduce the size of the argument of sin. (For purposes of this exercise an
  angle is considered ``sufficiently small'' if its magnitude is not greater
  than 0.1 radians.) These ideas are incorporated in the following procedures:
  #+BEGIN_SRC scheme
    (define (cube x) (* x x x))
    (define (p x) (- (* 3 x) (* 4 (cube x))))
    (define (sine angle)
      (if (not (> (abs angle) 0.1))
          angle
          (p (sine (/ angle 3.0)))))
  #+END_SRC
  a. How many times is the procedure ~p~ applied when ~(sine 12.15)~ is
     evaluated?
     ~p~ is applied 5 times.
  b. What is the order of growth in space and number of steps (as a function of
     /a/) used by the process generated by the ~sine~ procedure when ~(sine a)~
     is evaluated?
